### ISSUE TITLE
setup error 

### ISSUE THREAD

**Issue by chingshiung** [robscetury/gibson#20]
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    ext_modules= [Extension("gibson.physics.spring", "gibson/physics/spring.pyx")]
  File "/usr/lib/python2.7/distutils/extension.py", line 109, in **init**
    "'sources' must be a list of strings"
AssertionError: 'sources' must be a list of strings

can any one help :)

**Comment by robscetury** [comment]
Hi,

What version of python and which OS?

**Comment by chingshiung** [comment]
python2.7 ubuntu 12.04 :)

於 2013/11/19 下午 08:25, robscetury 提到:

> Hi,
> 
> What version of python and which OS?
> 
> On Tue, Nov 19, 2013 at 1:56 AM, chingshiung

**Comment by robscetury** [comment]
Thanks that should work,  could you make cython is installed?

**Comment by chingshiung** [comment]
1  ls
     2  cd vmware-tools-distrib/
     3  ls
     4  ./vmware-install.pl
     5  apt-get update
     6  apt-get upgrade
     7  ls
     8  reboot
     9  apt-get upgrade
    10  reboot
    11  apt-get update
    12  apt-get install git
    13  https://github.com/robscetury/gibson.git
    14  git clone https://github.com/robscetury/gibson.git
    15  pwd
    16  ls
    17  cd gibson/
    18  ls
    19  sudo apt-get install python-setuptools python-dev build-essential
    20  apt-get install python-pip
    21  apt-get install curl
    22  ls
    23  sh install_libraries.sh
    24  ls
    25  more ez_setup.py
    26  python ez_setup.py
    27  python ez_setup.py -U setup.py
    28  python ez_setup.py -U setuptools
    29  ls
    30  python setup.py
    31  sudo nano /etc/apt/sources.list.d/panda3d.list
    32  more /etc/apt/sources.list.d/panda3d.list
    33  apt-get update
    34  sudo apt-get install panda3d-runtime
    35  ls
    36  python setup.py
    37  ls
    38  cd cfg/
    39  ls
    40  cd ..
    41  ls
    42  more README
    43  more setup.py
    44  apt-cache search spring
    45  apt-get install spring
    46  ls
    47  python setup.py
    48  python
    49  apt-get install cpython
    50  ping www.google.com.tw
    51  apt-get install cpython
    52  apt-cache search cpython
    53  apt-get install libshiboken-dev
    54  ls
    55  /sbin/ifconfig
    56  ls
    57  python setup.py

Traceback (most recent call last):
   File "setup.py", line 7, in <module>
     ext_modules= [Extension("gibson.physics.spring", 
"gibson/physics/spring.pyx")]
   File "/usr/lib/python2.7/distutils/extension.py", line 109, in **init**
     "'sources' must be a list of strings"
AssertionError: 'sources' must be a list of strings

my ubuntu is new install :)

thanks

**Comment by FernandoHiagon** [comment]
Hi chingshiung and robscetury !
This is a amazing peace of code !
Im trying to install on Fedora 20 and i got the same error. Right now i'll test on ubuntu Lucid.
robscetury, can you tell me your OS and python version used to build and test gibson ?

Sorry about my english.
Best regards

**Comment by dklinedinst** [comment]
Hi FernandoHiagon,

This is Dan Klinedinst, I wrote the original Gibson code, although we have
not updated it in 3 years.  It uses whichever version of python is
installed by Panda 3D, I think 2.6.  If Panda is installed, ppython should
be in your path.

I did all of my original development on OS X because the video APIs change
a lot on different versions of Linux.  I think Ubuntu worked better than
CentOS but I didn't run on Linux much.

There's at least one new version of Panda since we published that code, too.

Dan

**Comment by FernandoHiagon** [comment]
Hello Dan !
First off, let me say congrats to your very good work.
I have installed panda3d on win7. After setting up paths on system environment ("export MODELPATH=blabla" to "SET MODELPATH=blabla"), Gibson works !. Some paths i cannot make it work, so i copied all files from images folder to /bin folder. Now i'll try on ubuntu.

One more time, thank you for your attention !
Best regards
Hiagon
www.hiagon.com
